### ISSUE TITLE
Package not auto-udated on packagist.org

### ISSUE THREAD

**Issue by kdambekalns** [lelesys/Lelesys.News#12]
It seems https://packagist.org/packages/lelesys/news is not updated (using the GitHub hook), so new tags do not appear (or only with a noticeable lag).

> Existing packages without auto-updating (GitHub/BitBucket hook) will be crawled once a week for updates.

See https://packagist.org/about#how-to-update-packages

**Comment by pankajlele** [comment]
It was already auto-updating but had an issue with composer.json in 2.3 branch quoted below. It is fixed now and 2.0.0 tag is recreated. Now https://packagist.org/packages/lelesys/news shows new tags. 

> Skipped branch 2.3, Invalid package information: 
> License "GPL-3.0+" is a deprecated SPDX license identifier, use "GPL-3.0-or-later" instead
