### ISSUE TITLE
Neos 5 or 7 Support?

### ISSUE THREAD

**Issue by stefkey** [lelesys/Lelesys.News#15]
Hi, I have updated my Neos. Now my newslist doesn't work anymore. Is there an update for Neos 5 or 7

**Comment by pankajlele** [comment]
Hello there. I have noted your message and i will try to release an update in this week. 

Pankaj Lele,

**Comment by stefkey** [comment]
That would be wonderful. Thanks a lot.

**Comment by pankajlele** [comment]
@stefkey I have just made an commit into master branch for Neos 5.x compatibility. If possible would you please try it out?
