### ISSUE TITLE
Category filter not working

### ISSUE THREAD

**Issue by 100hz** [lelesys/Lelesys.News#2]
Hi,

thank you you for your work on the NEOS extensions. They are a good point to start and learn NEOS development for me.

Currently the category filter does not work, i think.

```
newsCollection.@process.filterByCategories = ${filterByCategories != null && filterByCategories != '' ? q(value).filter('[categories *= \'' + filterByCategories + '\']').get() : value}
```

The above code in _List.ts2_ (https://github.com/lelesys/Lelesys.News/blob/master/Resources/Private/TypoScript/Prototypes/List.ts2#L32) seems to be ineffective.

It would be great if you could provide a solution for that.

Thanks in advance & best regards
Sebastian

**Comment by pankajlele** [comment]
This issue is already fixed. Closing issue.
